# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JWSDDay' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JWSDDay

  pod 'SwiftLint'

  pod 'SwiftDate'  

  target 'JWSDDayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JWSDDayUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
